[book]
title = "Asynchronous Programming in Rust"
authors = ["Taylor Cramer"]

[build]
create-missing = false

[preprocess.links]

[output.html]
git-repository-url = "https://github.com/rust-lang/async-book"
site-url = "/async-book/"
additional-js = ["assets/translate.js"]

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
